Fix dependencies for angular/cli
Should fix #1196

As explained in the above issue we were getting:

```
Running ['/home/lefteris/.npm-global/bin/npm', 'run', 'build:prod'] in '/home/lefteris/ew/raiden/raiden/ui/web'

> raidenwebui@0.2.0 build:prod /home/lefteris/ew/raiden/raiden/ui/web
> ng build --prod --aot

module.js:487
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lefteris/ew/raiden/raiden/ui/web/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raidenwebui@0.2.0 build:prod: `ng build --prod --aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raidenwebui@0.2.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lefteris/.npm/_logs/2018-01-24T11_36_30_610Z-debug.log
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    'raiden = raiden.__main__:main'
  File "/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 99, in run
    subprocess.check_call(command, cwd=cwd)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/lefteris/.npm-global/bin/npm', 'run', 'build:prod']' returned non-zero exit status 1.
```

A lot of other projects had this problem and the solution explained in this post
works: https://github.com/angular/angular-cli/issues/9307#issuecomment-359264655